---
name: 'Deploy Ansible Galaxy Collection'
description: 'Builds and deploys a Collection to Ansible Galaxy'
author: 'Artis3n <dev@artis3nal.com>'
inputs:
  api_key:
    description: Ansible Galaxy API key. We recommend you store this as a GitHub Secret.
    required: true
  collection_dir:
    description: The directory in which the Ansible Collection is stored. This defaults to the project root.
    required: false
    default: './'
  build:
    description: |
      You can now choose to build a collection without publishing, and vice versa.
      If you wish to disable building a collection, set this parameter to "false."
    required: true
    default: "true"
  publish:
    description: |
      You can now choose to publish a collection without building (from a pre-built archive), and vice versa.
      If you wish to disable publishing a collection, set this parameter to "false."
    required: true
    default: "true"
  galaxy_version:
    description: Dynamically inject a semver-compatible version into your galaxy.yml file.
    required: false
  galaxy_url:
    description: The Galaxy API server URL. Targets https://galaxy.ansible.com/ by default. Modify if you are using an alternate Galaxy server, such as RedHat Automation Hub.
    required: false
    default: 'https://galaxy.ansible.com'
#  galaxy_version_commit:
#    description: The Action will write the `galaxy_version` value into your `galaxy.yml` and commit it.
#    required: false
#  galaxy_version_increment:
#    description: |
#      The Action will read the version in galaxy.yml and increment it based on the value provided in this parameter.
#      Valid values are: `major`, `minor`, `patch`.
#      Defaults to `patch`.
#    required: false
#    default: patch
runs:
  using: 'docker'
  # Takes ~3 minutes to build the container so speed up consumer invocations by using pre-built image
  image: docker://ghcr.io/artis3n/ansible_galaxy_collection:v2.8.0
branding:
  icon: 'box'
  color: 'purple'
